# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=18, unique=True, verbose_name='\u5b66\u53f7/\u6559\u5e08\u53f7')),
                ('nickname', models.CharField(blank=True, max_length=24, null=True, verbose_name='\u6635\u79f0')),
                ('gender', models.PositiveIntegerField(choices=[(1, '\u7537'), (2, '\u5973')], default=1, verbose_name='\u6027\u522b')),
                ('name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('email', models.CharField(blank=True, max_length=56, null=True, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('qq', models.CharField(blank=True, max_length=28, null=True, verbose_name='qq')),
                ('identity', models.PositiveIntegerField(choices=[(1, '\u5b66\u751f'), (2, '\u8001\u5e08')], default=1, verbose_name='\u8eab\u4efd')),
                ('type', models.PositiveIntegerField(default=1, verbose_name='\u7c7b\u578b')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u6709\u6548')),
                ('is_admin', models.BooleanField(default=False, verbose_name='\u8d85\u7ea7\u7ba1\u7406\u5458')),
                ('class_id', models.IntegerField(blank=True, null=True, verbose_name='\u73ed\u7ea7')),
                ('director', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5177\u6709\u6307\u5bfc\u6743\u9650')),
                ('manage', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5177\u6709\u7ba1\u7406\u6743\u9650')),
                ('super', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5177\u6709\u8d85\u7ea7\u7ba1\u7406\u6743\u9650')),
                ('assigned_by', models.IntegerField(blank=True, null=True, verbose_name='\u6743\u9650\u662f\u88ab\u8c01\u8d4b\u4e88\u7684')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 't_user',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u5e74')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='\u73ed\u53f7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_class',
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
    ]
