# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='super',
        ),
        migrations.AlterField(
            model_name='tuser',
            name='class_id',
            field=models.ForeignKey(blank=True, db_column=b'class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TClass', verbose_name='\u73ed\u7ea7'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='identity',
            field=models.PositiveIntegerField(choices=[(1, '\u5b9e\u9a8c\u4eba\u5458'), (2, '\u5b9e\u9a8c\u6307\u5bfc'), (3, '\u7cfb\u7edf\u7ba1\u7406\u5458'), (4, '\u8d85\u7ea7\u7ba1\u7406\u5458')], default=1, verbose_name='\u8eab\u4efd'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '\u5b66\u751f'), (2, '\u8001\u5e08')], default=1, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='username',
            field=models.CharField(db_index=True, max_length=18, unique=True, verbose_name='\u8d26\u53f7'),
        ),
    ]
