# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170208_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='class_id',
        ),
        migrations.AddField(
            model_name='tuser',
            name='tclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TClass', verbose_name='\u73ed\u7ea7'),
        ),
    ]
