# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_tuser_is_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='tclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.TClass', verbose_name='\u73ed\u7ea7'),
        ),
    ]
