# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170420_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_company',
                'verbose_name': '\u5355\u4f4d',
                'verbose_name_plural': '\u5355\u4f4d',
            },
        ),
        migrations.AddField(
            model_name='tuser',
            name='is_share',
            field=models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5171\u4eab'),
        ),
        migrations.AddField(
            model_name='tuser',
            name='last_experiment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6700\u540e\u505a\u7684\u4e00\u4e2a\u5b9e\u9a8cid'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u8d26\u53f7\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='is_register',
            field=models.BooleanField(default=False, verbose_name='\u73af\u4fe1\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='qq',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='tuser',
            name='tcompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.TCompany', verbose_name='\u6240\u5728\u5355\u4f4d'),
        ),
    ]
