# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190404_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'avatars'),
        ),
    ]
