# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-11 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190411_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='create_time',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
