# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-18 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190411_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='name',
            field=models.CharField(max_length=256, verbose_name='\u59d3\u540d'),
        ),
    ]
