# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-22 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190418_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='roles',
        ),
    ]
