# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-22 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_tuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='roles',
            field=models.ManyToManyField(to='account.TRole'),
        ),
    ]
