# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-22 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_tcompany_group'),
        ('account', '0015_tuser_roles'),
    ]

    operations = [
    ]
