# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-23 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_tcompanymanagers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_officeItems',
            },
        ),
        migrations.CreateModel(
            name='OfficeKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_officeKinds',
            },
        ),
        migrations.AddField(
            model_name='officeitems',
            name='kinds',
            field=models.ManyToManyField(to='account.OfficeKinds'),
        ),
        migrations.AddField(
            model_name='tuser',
            name='instructorItems',
            field=models.ManyToManyField(to='account.OfficeItems'),
        ),
    ]
