# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_tcompanymanagers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='tcompany',
        ),
    ]
