# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_tuser_tcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='tcompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.TCompany', verbose_name='\u6240\u5728\u5355\u4f4d'),
        ),
    ]
