# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_tcompany_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcompany',
            name='manager',
        ),
    ]
