# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_tuser_tcompany'),
        ('account', '0020_remove_tcompany_manager'),
    ]

    operations = [
    ]
