# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_merge_20190425_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_companyType',
            },
        ),
        migrations.AddField(
            model_name='tcompany',
            name='created_by',
            field=models.ForeignKey(default=1639, on_delete=django.db.models.deletion.CASCADE, related_name='created_company_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
