# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20190425_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcompany',
            name='companyType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.TCompanyType'),
            preserve_default=False,
        ),
    ]
