# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-26 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_tcompany_companytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcompany',
            name='comment',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
