# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-26 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_tcompany_comment'),
        ('account', '0023_loginlog'),
    ]

    operations = [
    ]
