# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-26 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_merge_20190426_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcompany',
            name='assistants',
            field=models.ManyToManyField(related_name='t_company_set_assistants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TCompany'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.AllGroups'),
        ),
    ]
