# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-27 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20190426_2054'),
        ('account', '0027_auto_20190426_2122'),
    ]

    operations = [
    ]
