# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-27 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_merge_20190427_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-login_time'], 'verbose_name': '\u767b\u5f55\u8bb0\u5f55', 'verbose_name_plural': '\u767b\u5f55\u8bb0\u5f55'},
        ),
    ]
