# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20190430_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeitems',
            name='content',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officeitems',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='officeitems',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='officekinds',
            name='content',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officekinds',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='officekinds',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
