# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_tcoursetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCourseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_courseItems',
            },
        ),
        migrations.CreateModel(
            name='TCourseKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_courseKinds',
            },
        ),
        migrations.DeleteModel(
            name='TCourseType',
        ),
        migrations.AddField(
            model_name='tcourseitems',
            name='kinds',
            field=models.ManyToManyField(to='account.TCourseKinds'),
        ),
    ]
