# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-02 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20190430_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='class_name',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
