# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20190502_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='is_review',
            field=models.IntegerField(default=0),
        ),
    ]
