# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_tuser_is_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcompany',
            name='is_default',
            field=models.IntegerField(default=0),
        ),
    ]
