# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-06 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_tcompany_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TCompany')),
            ],
            options={
                'db_table': 't_parts',
            },
        ),
        migrations.CreateModel(
            name='TPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TParts')),
            ],
            options={
                'db_table': 't_positions',
            },
        ),
    ]
