# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-06 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_tparts_tpositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='tposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TPositions'),
        ),
    ]
