# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-08 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_tcompanychange'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
                ('codename', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
            ],
            options={
                'db_table': 't_action',
                'verbose_name': 'Permission Action',
                'verbose_name_plural': 'Permission Actions',
            },
        ),
        migrations.CreateModel(
            name='TPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
                ('codename', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
            ],
            options={
                'db_table': 't_permission',
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.AddField(
            model_name='taction',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TPermission'),
        ),
    ]
