# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20190509_1117'),
        ('account', '0043_auto_20190508_2049'),
    ]

    operations = [
    ]
