# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_merge_20190509_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TInnerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=256)),
                ('ownPositions', models.ManyToManyField(to='account.TPositions')),
            ],
            options={
                'db_table': 't_innerPermission',
            },
        ),
    ]
