# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-12 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_tinnerpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=b'', max_length=256)),
                ('content', models.CharField(default=b'', max_length=256)),
                ('link', models.CharField(default=b'', max_length=256)),
                ('mode', models.IntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TRole')),
                ('targets', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_notification',
            },
        ),
    ]
