# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20190515_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinnerpermission',
            name='ownPositions',
        ),
        migrations.RemoveField(
            model_name='tnotifications',
            name='role',
        ),
        migrations.RemoveField(
            model_name='tnotifications',
            name='targets',
        ),
        migrations.DeleteModel(
            name='TInnerPermission',
        ),
        migrations.DeleteModel(
            name='TNotifications',
        ),
    ]
