# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20190515_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='TInnerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=256)),
                ('ownPositions', models.ManyToManyField(to='account.TPositions')),
            ],
            options={
                'db_table': 't_innerPermission',
            },
        ),
        migrations.CreateModel(
            name='TNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=b'', max_length=256)),
                ('content', models.CharField(default=b'', max_length=256)),
                ('link', models.CharField(default=b'', max_length=256)),
                ('mode', models.IntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TRole')),
                ('targets', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_notification',
            },
        ),
        migrations.AddField(
            model_name='tcompany',
            name='assistants',
            field=models.ManyToManyField(related_name='t_company_set_assistants', to=settings.AUTH_USER_MODEL),
        ),
    ]
