# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20190515_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taction',
            name='permission',
        ),
        migrations.DeleteModel(
            name='TAction',
        ),
    ]
