# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_remove_tcompany_assistants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcompany',
            name='assistants',
            field=models.ManyToManyField(related_name='t_company_set_assistants', to=settings.AUTH_USER_MODEL),
        ),
    ]
