# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_tcompany_assistants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcompany',
            name='assistants',
        ),
    ]
