# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_remove_tcompany_assistants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCompanyManagerAssistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.ManyToManyField(to='account.TAction')),
                ('tcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TCompany')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_company_assistants',
            },
        ),
    ]
