# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-18 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0028_auto_20190515_2240'),
        ('account', '0059_trole_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_at', models.DateTimeField(auto_now_add=True, verbose_name='log at')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('action', models.CharField(max_length=256, verbose_name='action Name')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TCompany')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.AllGroups')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_at'],
                'db_table': 't_work_logs',
                'verbose_name': '\u64cd\u4f5c\u65e5\u5fd7',
                'verbose_name_plural': '\u64cd\u4f5c\u65e5\u5fd7',
            },
        ),
    ]
