# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_auto_20190522_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=48)),
            ],
            options={
                'db_table': 't_course',
            },
        ),
    ]
