# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-23 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_worklog_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='request_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Request Url'),
        ),
    ]
