# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_merge_20190526_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='last_business_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6700\u540e\u505a\u7684\u4e00\u4e2aBusinessId'),
        ),
    ]
