# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_tuser_last_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
