# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_tuser_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcourse',
            name='name',
        ),
        migrations.AddField(
            model_name='tcourse',
            name='courseName',
            field=models.CharField(default='\u6d4b\u8bd5\u8bfe\u7a0b', max_length=48, verbose_name='courseName'),
            preserve_default=False,
        ),
    ]
