# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20190816_1846'),
        ('account', '0068_tuser_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='linked_courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
