# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58, verbose_name='\u540d\u79f0')),
                ('app', models.FileField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'files/', verbose_name='APP\u5e94\u7528')),
                ('url', models.CharField(max_length=128, verbose_name='\u4e0b\u8f7d\u94fe\u63a5')),
                ('version', models.IntegerField(verbose_name='\u7248\u672c\u53f7')),
                ('type', models.PositiveIntegerField(verbose_name='\u7c7b\u578b')),
                ('remark', models.CharField(max_length=256, verbose_name='\u8bf4\u660e')),
                ('total', models.IntegerField(verbose_name='\u4e0b\u8f7d\u7edf\u8ba1')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_app_release',
                'verbose_name': 'APP\u7248\u672c\u53d1\u5e03',
                'verbose_name_plural': 'APP\u7248\u672c\u53d1\u5e03',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='\u4e0a\u7ea7')),
                ('name', models.CharField(max_length=48, verbose_name='\u540d\u79f0')),
                ('code', models.CharField(max_length=48, verbose_name='\u4ee3\u7801')),
                ('style', models.CharField(blank=True, max_length=24, null=True, verbose_name='\u6837\u5f0f')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u94fe\u63a5')),
                ('target', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u76ee\u6807')),
                ('visible', models.PositiveIntegerField(verbose_name='\u663e\u793a\u72b6\u6001')),
                ('sort', models.IntegerField(verbose_name='\u5c55\u793a\u6392\u5e8f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_module',
                'verbose_name': '\u529f\u80fd\u6a21\u5757\u83dc\u5355',
                'verbose_name_plural': '\u529f\u80fd\u6a21\u5757\u83dc\u5355',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=48, verbose_name='key')),
                ('value', models.CharField(max_length=256, verbose_name='\u503c')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u540d\u79f0')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u8bf4\u660e')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_parameter',
                'verbose_name': '\u53c2\u6570\u914d\u7f6e',
                'verbose_name_plural': '\u53c2\u6570\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, verbose_name='key')),
                ('value', models.IntegerField(verbose_name='\u503c')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 't_sequence',
                'verbose_name': '\u5e8f\u53f7',
                'verbose_name_plural': '\u5e8f\u53f7',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128, verbose_name='\u6587\u4ef6\u540d')),
                ('file', models.FileField(storage=utils.storage.CheckSumFileStoreage(), upload_to=b'files/', verbose_name='\u6587\u4ef6')),
                ('md5sum', models.CharField(max_length=128, verbose_name='MD5\u54c8\u5e0c\u503c')),
                ('created_by', models.IntegerField(verbose_name='\u4e0a\u4f20\u8005')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_upload_file',
                'verbose_name': '\u6587\u4ef6',
                'verbose_name_plural': '\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('username', models.CharField(blank=True, max_length=28, null=True, verbose_name='\u7528\u6237\u8d26\u53f7')),
                ('method', models.CharField(blank=True, max_length=68, null=True, verbose_name='\u8c03\u7528\u65b9\u6cd5')),
                ('param', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u53c2\u6570')),
                ('result', models.CharField(blank=True, max_length=518, null=True, verbose_name='\u7ed3\u679c')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='url')),
                ('ip', models.CharField(blank=True, max_length=28, null=True, verbose_name='ip')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_user_logs',
                'verbose_name': '\u7528\u6237\u65e5\u5fd7',
                'verbose_name_plural': '\u7528\u6237\u65e5\u5fd7',
            },
        ),
    ]
