# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='app',
            field=models.FileField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'app/', verbose_name='APP\u5e94\u7528'),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'android'), (2, 'ios'), (3, 'wechat')], default=1, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(storage=utils.storage.FileStorage(), upload_to=b'files/%Y/%m/%d', verbose_name='\u6587\u4ef6'),
        ),
    ]
