# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20170331_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='\u4e0a\u4f20\u8005'),
        ),
    ]
