# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=16, verbose_name='\u8bfe\u7a0b\u53f7')),
                ('name', models.CharField(max_length=48, verbose_name='\u540d\u79f0')),
                ('time', models.IntegerField(verbose_name='\u8bfe\u65f6')),
                ('sort', models.IntegerField(verbose_name='\u8bfe\u5e8f\u53f7')),
                ('teacher1', models.IntegerField(verbose_name='\u6559\u5e08\u53f71')),
                ('teacher2', models.IntegerField(verbose_name='\u6559\u5e08\u53f72')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_course',
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
    ]
