# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='no',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u8bfe\u7a0b\u53f7'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8bfe\u5e8f\u53f7'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher1',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6559\u5e08\u53f71'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher2',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6559\u5e08\u53f72'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8bfe\u65f6'),
        ),
    ]
