# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20170207_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=16, verbose_name='\u8bfe\u7a0b\u53f7')),
                ('name', models.CharField(max_length=48, verbose_name='\u540d\u79f0')),
                ('time', models.IntegerField(verbose_name='\u8bfe\u65f6')),
                ('sort', models.IntegerField(verbose_name='\u8bfe\u5e8f\u53f7')),
                ('term', models.CharField(max_length=24, verbose_name='\u5f00\u8bfe\u65e5\u671f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('teacher1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher1', to=settings.AUTH_USER_MODEL, verbose_name='\u6559\u5e08\u53f71')),
                ('teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher2', to=settings.AUTH_USER_MODEL, verbose_name='\u6559\u5e08\u53f72')),
            ],
            options={
                'db_table': 't_course_class',
                'verbose_name': '\u8bfe\u5802',
                'verbose_name_plural': '\u8bfe\u5802',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='del_flag',
        ),
        migrations.RemoveField(
            model_name='course',
            name='no',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='update_time',
        ),
    ]
