# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-04 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20170210_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 't_course_class_student',
                'verbose_name': '\u8bfe\u5802\u5b66\u751f\u5173\u8054',
                'verbose_name_plural': '\u8bfe\u5802\u5b66\u751f\u5173\u8054',
            },
        ),
        migrations.AddField(
            model_name='courseclass',
            name='experiment_time',
            field=models.IntegerField(null=True, verbose_name='\u5b9e\u9a8c\u5b66\u65f6'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='is_share',
            field=models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5171\u4eab'),
        ),
        migrations.AddField(
            model_name='courseclassstudent',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClass', verbose_name='\u8bfe\u5802'),
        ),
        migrations.AddField(
            model_name='courseclassstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5b66\u751f'),
        ),
    ]
