# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-17 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0065_tuser_last_business_id'),
        ('course', '0004_auto_20190404_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='teacher1',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='teacher2',
        ),
        migrations.RemoveField(
            model_name='courseclassstudent',
            name='course_class',
        ),
        migrations.RemoveField(
            model_name='courseclassstudent',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u8bfe\u5802', 'verbose_name_plural': '\u8bfe\u5802'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='courseCount',
            field=models.IntegerField(default=0, verbose_name='courseCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='courseId',
            field=models.CharField(default=123, max_length=16, verbose_name='courseId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='courseName',
            field=models.CharField(default='teat', max_length=48, verbose_name='courseName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='courseSemester',
            field=models.CharField(default=3, max_length=48, verbose_name='courseSemester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='courseSeqNum',
            field=models.IntegerField(default=3, verbose_name='courseSeqNum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default=1760, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='experienceTime',
            field=models.CharField(default=2010, max_length=48, verbose_name='experienceTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='studentCount',
            field=models.IntegerField(default=5, verbose_name='studentCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tcompany',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='account.TCompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacherId',
            field=models.CharField(default=14235346, max_length=48, verbose_name='teacherId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacherName',
            field=models.CharField(default='wow', max_length=48, verbose_name='teacherName'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseClass',
        ),
        migrations.DeleteModel(
            name='CourseClassStudent',
        ),
    ]
