# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-17 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0065_tuser_last_business_id'),
        ('course', '0005_auto_20190717_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityLinkedCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('seted_time', models.DateTimeField(verbose_name='seted_time')),
                ('message', models.CharField(max_length=100, verbose_name='message')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('linked_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_company_set', to='account.TCompany')),
                ('seted_company_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seted_company_manager', to='account.TCompany')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_set', to='account.TCompany')),
            ],
            options={
                'db_table': 't_university_linked_company',
                'verbose_name': 'UniversityLinkedCompany',
                'verbose_name_plural': 'UniversityLinkedCompany',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='del_flag',
            field=models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664'),
        ),
    ]
