# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_auto_20190717_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacherId',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacherName',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1605, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
        migrations.AlterField(
            model_name='universitylinkedcompany',
            name='seted_company_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seted_company_manager', to='account.TCompanyManagers'),
        ),
    ]
