# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190717_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitylinkedcompany',
            name='seted_company_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seted_company_manager', to='account.TCompanyManagers'),
        ),
    ]
