# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190718_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.IntegerField(default=0, verbose_name='type'),
        ),
    ]
