# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190717_1903'),
        ('course', '0008_course_type'),
    ]

    operations = [
    ]
