# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_merge_20190719_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCount',
            field=models.IntegerField(null=True, verbose_name='courseCount'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseId',
            field=models.CharField(max_length=16, null=True, verbose_name='courseId'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseSemester',
            field=models.CharField(max_length=48, null=True, verbose_name='courseSemester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseSeqNum',
            field=models.IntegerField(null=True, verbose_name='courseSeqNum'),
        ),
        migrations.AlterField(
            model_name='course',
            name='experienceTime',
            field=models.CharField(max_length=48, null=True, verbose_name='experienceTime'),
        ),
        migrations.AlterField(
            model_name='course',
            name='studentCount',
            field=models.IntegerField(null=True, verbose_name='studentCount'),
        ),
    ]
