# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-19 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190719_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitylinkedcompany',
            name='seted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='seted_time'),
        ),
    ]
