# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-22 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190719_0009'),
        ('course', '0010_auto_20190719_1343'),
    ]

    operations = [
    ]
