# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-16 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0014_auto_20190816_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
