# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManagers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_groupManagers',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('comment', models.CharField(max_length=256)),
                ('publish', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=1)),
                ('groupManager_ids', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_groups',
            },
        ),
    ]
