# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='default',
            field=models.IntegerField(default=0),
        ),
    ]
