# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-18 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_auto_20190418_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('comment', models.CharField(max_length=256)),
                ('publish', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=1)),
                ('default', models.IntegerField(default=0)),
                ('groupManagers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_allGroups',
            },
        ),
        migrations.RemoveField(
            model_name='groupmanagers',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmanagers',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupManagers',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
