# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20190418_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
