# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-23 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_allgroups_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_officeItems',
            },
        ),
        migrations.CreateModel(
            name='OfficeKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_officeKinds',
            },
        ),
        migrations.AddField(
            model_name='allgroups',
            name='groupInstructors',
            field=models.ManyToManyField(related_name='groupInstructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allgroups',
            name='groupManagers',
            field=models.ManyToManyField(related_name='groupManagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeitems',
            name='kinds',
            field=models.ManyToManyField(to='group.OfficeKinds'),
        ),
    ]
