# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-26 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0009_auto_20190425_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='groupInstructorAssistants',
            field=models.ManyToManyField(related_name='allgroups_set_instructor_assistants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allgroups',
            name='groupManagerAssistants',
            field=models.ManyToManyField(related_name='allgroups_set_assistants', to=settings.AUTH_USER_MODEL),
        ),
    ]
