# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-04 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_tgroupchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgroupchange',
            name='reason',
            field=models.CharField(default='', max_length=256),
        ),
    ]
