# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-04 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20190504_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgroupchange',
            name='target',
        ),
        migrations.RemoveField(
            model_name='tgroupchange',
            name='user',
        ),
        migrations.DeleteModel(
            name='TGroupChange',
        ),
    ]
