# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-04 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0013_auto_20190504_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGroupChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=256)),
                ('sAgree', models.IntegerField(default=0)),
                ('tAgree', models.IntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.AllGroups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_group_change',
            },
        ),
    ]
