# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-08 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0043_auto_20190508_2101'),
        ('group', '0016_tgroupchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGroupManagerAssistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TAction')),
                ('all_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.AllGroups')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TPermission')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_allGroups_groupManagerAssistants',
            },
        ),
    ]
