# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-08 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_auto_20190508_2110'),
        ('group', '0019_auto_20190508_2114'),
    ]

    operations = [
    ]
