# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0022_tgroupmanagerassistants_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgroupmanagerassistants',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='tgroupmanagerassistants',
            name='all_groups',
        ),
        migrations.RemoveField(
            model_name='tgroupmanagerassistants',
            name='tuser',
        ),
        migrations.RemoveField(
            model_name='allgroups',
            name='groupManagerAssistants',
        ),
        migrations.DeleteModel(
            name='TGroupManagerAssistants',
        ),
    ]
