# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_auto_20190515_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='groupManagerAssistants',
        ),
    ]
