# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-15 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0058_tcompany_assistants'),
        ('group', '0027_auto_20190515_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGroupManagerAssistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.ManyToManyField(to='account.TAction')),
                ('all_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.AllGroups')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_allGroups_groupManagerAssistants',
            },
        ),
        migrations.AddField(
            model_name='allgroups',
            name='groupManagerAssistants',
            field=models.ManyToManyField(related_name='allgroups_set_assistants', through='group.TGroupManagerAssistants', to=settings.AUTH_USER_MODEL),
        ),
    ]
