# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_advertising_public_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='public_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
