# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-31 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0038_projectnodeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('huanxin_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u73af\u4fe1id')),
                ('show_nickname', models.BooleanField(default=False, verbose_name='\u6635\u79f0\u663e\u793a\u7ec4\u5458')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('status', models.PositiveIntegerField(choices=[(1, '\u7b49\u5f85\u4e2d'), (2, '\u8fdb\u884c\u4e2d'), (9, '\u5df2\u7ed3\u675f')], default=1, verbose_name='\u72b6\u6001')),
                ('node_id', models.IntegerField(blank=True, null=True, verbose_name='\u5f53\u524d\u73af\u8282')),
                ('path_id', models.IntegerField(blank=True, null=True, verbose_name='\u5f53\u524d\u8def\u5f84')),
                ('cur_project_id', models.IntegerField(blank=True, null=True, verbose_name='\u5f53\u524d\u9879\u76ee')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b9e\u9645\u5b8c\u6210\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='\u9879\u76ee')),
            ],
            options={
                'ordering': ('-create_time',),
                'db_table': 't_business',
                'verbose_name': 'Business',
                'verbose_name_plural': 'Business',
            },
        ),
    ]
