# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-04 02:09
from __future__ import unicode_literals

import business.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_merge_20190526_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0056_flowroleallocation_can_start'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField(blank=True, null=True, verbose_name='\u5b9e\u9a8c\u8def\u5f84')),
                ('filename', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('file', models.FileField(storage=utils.storage.FileStorage(), upload_to=business.models.get_business_doc_upload_to, verbose_name='\u6587\u4ef6')),
                ('file_type', models.PositiveSmallIntegerField(choices=[(0, '\u6587\u4ef6'), (1, '\u6587\u6863'), (2, '\u56fe\u7247'), (3, '\u89c6\u9891'), (4, '\u97f3\u9891')], default=0, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('sign', models.CharField(blank=True, max_length=12, null=True, verbose_name='\u7b7e\u540d')),
                ('sign_status', models.BooleanField(default=False, verbose_name='\u7b7e\u540d\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 't_business_doc',
                'verbose_name': 'BusinessDoc',
                'verbose_name_plural': 'BusinessDoc',
            },
        ),
        migrations.CreateModel(
            name='BusinessDocTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('business_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessDoc', verbose_name='BusinessDoc')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('type', models.CharField(max_length=28, verbose_name='\u89d2\u8272\u7c7b\u578b')),
                ('image_id', models.IntegerField(null=True, verbose_name='\u89d2\u8272\u5f62\u8c61')),
                ('category', models.PositiveIntegerField(null=True, verbose_name='\u7c7b\u522b')),
                ('capacity', models.IntegerField(default=1, verbose_name='\u4eba\u6570')),
                ('flow_role_id', models.IntegerField(verbose_name='\u6d41\u7a0b\u89d2\u8272id')),
                ('project_role_id', models.IntegerField(verbose_name='Project Role Id')),
            ],
            options={
                'db_table': 't_business_role',
                'verbose_name': 'BusinessRole',
                'verbose_name_plural': 'BusinessRole',
            },
        ),
        migrations.CreateModel(
            name='BusinessRoleAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_terminate', models.BooleanField(verbose_name='\u7ed3\u675f\u73af\u8282\u6743\u9650')),
                ('can_brought', models.BooleanField(verbose_name='\u662f\u5426\u88ab\u5e26\u5165')),
                ('can_take_in', models.BooleanField(default=False, verbose_name='This guy will be taken in this step ')),
                ('can_start', models.BooleanField(default=False, verbose_name='Can Start the business')),
                ('no', models.IntegerField(default=1, verbose_name='Number')),
            ],
            options={
                'db_table': 't_business_role_allocation',
                'verbose_name': 'Business Role Allocation',
                'verbose_name_plural': 'Business Role Allocation',
            },
        ),
        migrations.CreateModel(
            name='BusinessTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'ordering': ('-create_time',),
                'db_table': 't_business_team',
                'verbose_name': 'BusinessTeam',
                'verbose_name_plural': 'BusinessTeam',
            },
        ),
        migrations.RemoveField(
            model_name='business',
            name='node_id',
        ),
        migrations.AddField(
            model_name='business',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.FlowNode', verbose_name='\u5f53\u524d\u73af\u8282'),
        ),
        migrations.AddField(
            model_name='businessteam',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='businessteam',
            name='business_role_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation'),
        ),
        migrations.AddField(
            model_name='businessteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='businessroleallocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u4efb\u52a1'),
        ),
        migrations.AddField(
            model_name='businessroleallocation',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282'),
        ),
        migrations.AddField(
            model_name='businessroleallocation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRole', verbose_name='\u89d2\u8272'),
        ),
        migrations.AddField(
            model_name='businessrole',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u4efb\u52a1'),
        ),
        migrations.AddField(
            model_name='businessrole',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.TJobType'),
        ),
        migrations.AddField(
            model_name='businessdocteam',
            name='business_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessTeam', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='businessdoc',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='businessdoc',
            name='business_role_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation'),
        ),
        migrations.AddField(
            model_name='businessdoc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
        migrations.AddField(
            model_name='businessdoc',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282'),
        ),
    ]
