# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-04 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190604_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdocteam',
            options={'ordering': ['-create_time'], 'verbose_name': 'BusinessDocTeam', 'verbose_name_plural': 'BusinessDocTeam'},
        ),
        migrations.AlterModelTable(
            name='businessdocteam',
            table='t_business_doc_team',
        ),
    ]
