# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190604_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessteam',
            name='business_role_allocation',
        ),
        migrations.AddField(
            model_name='businessteam',
            name='business_role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRole', verbose_name='Business Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessteam',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
    ]
