# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_merge_20190526_1404'),
        ('business', '0005_businessteam_del_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='officeItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.OfficeItems'),
        ),
    ]
