# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businesstranspath'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRoleAllocationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speak_times', models.IntegerField(default=0, verbose_name='\u53d1\u8a00\u6b21\u6570')),
                ('submit_status', models.PositiveIntegerField(choices=[(1, '\u672a\u63d0\u4ea4'), (2, '\u5df2\u63d0\u4ea4'), (9, '\u672a\u5904\u7406')], default=9, verbose_name='\u63d0\u4ea4\u72b6\u6001')),
                ('show_status', models.PositiveIntegerField(choices=[(1, '\u5df2\u540c\u610f'), (2, '\u672a\u540c\u610f'), (9, '\u672a\u5904\u7406')], default=9, verbose_name='\u5c55\u793a\u72b6\u6001')),
                ('come_status', models.PositiveIntegerField(choices=[(1, '\u5f85\u5e26\u5165'), (2, '\u5f85\u9001\u51fa'), (9, '\u666e\u901a\u72b6\u6001')], default=9, verbose_name='\u5e26\u5165\u5e26\u51fa\u72b6\u6001')),
                ('sitting_status', models.PositiveIntegerField(choices=[(1, '\u672a\u5165\u5e2d'), (2, '\u5df2\u5165\u5e2d')], default=1, verbose_name='\u5165\u5e2d\u9000\u5e2d\u72b6\u6001')),
                ('stand_status', models.PositiveIntegerField(choices=[(1, '\u8d77\u7acb'), (2, '\u5750\u4e0b')], default=2, verbose_name='\u8d77\u7acb\u5750\u4e0b\u72b6\u6001')),
                ('vote_status', models.PositiveIntegerField(choices=[(0, '\u672a\u6295\u7968'), (1, '\u540c\u610f'), (2, '\u4e0d\u540c\u610f'), (9, '\u5f03\u6743')], default=0, verbose_name='\u6295\u7968\u72b6\u6001')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u4efb\u52a1')),
                ('business_role_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessTransPath', verbose_name='\u5b9e\u9a8c\u8def\u5f84')),
            ],
            options={
                'db_table': 't_business_role_allocation_status',
                'verbose_name': '\u5b9e\u9a8c\u73af\u8282\u89d2\u8272\u72b6\u6001',
                'verbose_name_plural': '\u5b9e\u9a8c\u73af\u8282\u89d2\u8272\u72b6\u6001',
            },
        ),
        migrations.RenameModel(
            old_name='BusinessTeam',
            new_name='BusinessTeamMember',
        ),
        migrations.RenameField(
            model_name='businessdocteam',
            old_name='business_team',
            new_name='business_team_member',
        ),
        migrations.AlterModelTable(
            name='businessteammember',
            table='t_business_team_member',
        ),
    ]
