# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20190605_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrole',
            name='project_id',
            field=models.IntegerField(null=True, verbose_name='\u5f53\u524d\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='businessroleallocation',
            name='project_id',
            field=models.IntegerField(null=True, verbose_name='\u5f53\u524d\u9879\u76ee'),
        ),
    ]
