# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_businessteammember_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='project',
        ),
        migrations.RemoveField(
            model_name='businesstranspath',
            name='project',
        ),
        migrations.AddField(
            model_name='business',
            name='project_id',
            field=models.IntegerField(null=True, verbose_name='\u5f53\u524d\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='businesstranspath',
            name='project_id',
            field=models.IntegerField(null=True, verbose_name='\u5f53\u524d\u9879\u76ee'),
        ),
    ]
