# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-07 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_tuser_last_business_id'),
        ('business', '0011_auto_20190606_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='target_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TCompany'),
        ),
        migrations.AddField(
            model_name='business',
            name='target_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TParts'),
        ),
    ]
