# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20190607_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '\u7b49\u5f85\u4e2d'), (2, '\u8fdb\u884c\u4e2d'), (9, '\u5df2\u7ed3\u675f')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
