# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_businessmessage_businessmessagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPositionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.IntegerField(verbose_name='\u5360\u4f4d')),
                ('sitting_status', models.PositiveIntegerField(choices=[(1, '\u672a\u5165\u5e2d'), (2, '\u5df2\u5165\u5e2d')], default=1, verbose_name='\u5165\u5e2d\u9000\u5e2d\u72b6\u6001')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u4efb\u52a1')),
                ('business_role_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessTransPath', verbose_name='\u5b9e\u9a8c\u8def\u5f84')),
            ],
            options={
                'db_table': 't_business_position_status',
                'verbose_name': '\u5b9e\u9a8c\u4efb\u52a1\u573a\u666f\u5360\u4f4d\u72b6\u6001',
                'verbose_name_plural': '\u5b9e\u9a8c\u4efb\u52a1\u573a\u666f\u5360\u4f4d\u72b6\u6001',
            },
        ),
    ]
