# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businesspositionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessroleallocation',
            name='flow_role_alloc_id',
            field=models.IntegerField(null=True, verbose_name='FlowRoleAlloction ID'),
        ),
        migrations.AddField(
            model_name='businessroleallocation',
            name='project_role_alloc_id',
            field=models.IntegerField(null=True, verbose_name='ProjectRoleAlloction ID'),
        ),
    ]
