# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-09 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20190607_1906'),
        ('business', '0014_auto_20190609_1933'),
    ]

    operations = [
    ]
