# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-12 12:30
from __future__ import unicode_literals

import business.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0059_processroleallocationaction'),
        ('business', '0016_businessreportstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u6a21\u677f\u540d\u79f0')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('file', models.FileField(blank=True, null=True, storage=utils.storage.FileStorage(), upload_to=business.models.get_business_doc_upload_to, verbose_name='\u6587\u4ef6')),
                ('sign', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7b7e\u540d')),
                ('sign_status', models.PositiveIntegerField(choices=[(0, '\u7b49\u5f85'), (1, '\u5df2\u7b7e\u5b57'), (2, '\u62d2\u7edd\u7b7e\u5b57')], default=0, verbose_name='\u7b7e\u540d\u72b6\u6001')),
                ('file_type', models.PositiveSmallIntegerField(choices=[(0, '\u6587\u4ef6'), (1, '\u6587\u6863'), (2, '\u56fe\u7247'), (3, '\u89c6\u9891'), (4, '\u97f3\u9891')], default=0, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('has_edited', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7f16\u8f91')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business')),
                ('business_role_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 't_business_doc_content',
                'verbose_name': '\u7528\u6237\u7f16\u8f91\u6a21\u7248\u5185\u5bb9',
                'verbose_name_plural': '\u7528\u6237\u7f16\u8f91\u6a21\u7248\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='BusinessDocSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(blank=True, max_length=18, null=True, verbose_name='\u7b7e\u540d')),
                ('sign_status', models.PositiveIntegerField(choices=[(0, '\u7b49\u5f85'), (1, '\u5df2\u7b7e\u5b57'), (2, '\u62d2\u7edd\u7b7e\u5b57')], default=0, verbose_name='\u7b7e\u540d\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business')),
                ('business_role_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 't_business_doc_sign',
                'verbose_name': '\u5b9e\u9a8c\u73af\u8282\u6587\u6863\u7b7e\u5b57\u8bb0\u5f55',
                'verbose_name_plural': '\u5b9e\u9a8c\u73af\u8282\u6587\u6863\u7b7e\u5b57\u8bb0\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='businessdoc',
            name='path_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5f53\u524d\u8def\u5f84'),
        ),
        migrations.AddField(
            model_name='businessdocsign',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessDoc', verbose_name='BusinessDoc'),
        ),
        migrations.AddField(
            model_name='businessdocsign',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282'),
        ),
        migrations.AddField(
            model_name='businessdoccontent',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessDoc', verbose_name='BusinessDoc'),
        ),
        migrations.AddField(
            model_name='businessdoccontent',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282'),
        ),
    ]
