# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-12 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0059_processroleallocationaction'),
        ('business', '0017_auto_20190612_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282')),
            ],
            options={
                'db_table': 't_business_notes',
                'verbose_name': '\u5b9e\u9a8c\u73af\u8282\u7b14\u8bb0',
                'verbose_name_plural': '\u5b9e\u9a8c\u73af\u8282\u7b14\u8bb0',
            },
        ),
        migrations.AlterField(
            model_name='businessdoc',
            name='business_role_allocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation'),
        ),
        migrations.AlterField(
            model_name='businessdoccontent',
            name='business_role_allocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation'),
        ),
        migrations.AlterField(
            model_name='businessdocsign',
            name='business_role_allocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessRoleAllocation', verbose_name='Business Role Allocation'),
        ),
    ]
