# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-18 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20190614_2017'),
        ('business', '0019_auto_20190618_0144'),
    ]

    operations = [
    ]
