# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-18 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0020_merge_20190618_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u5fc3\u5f97')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '\u672a\u63d0\u4ea4'), (2, '\u5df2\u63d0\u4ea4'), (9, '\u672a\u5904\u7406')], default=1, verbose_name='\u63d0\u4ea4\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u5b9e\u9a8c')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 't_business_experience',
                'verbose_name': '\u5b9e\u9a8c\u5fc3\u5f97',
                'verbose_name_plural': '\u5b9e\u9a8c\u5fc3\u5f97',
            },
        ),
    ]
