# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-24 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0022_remove_businessdocsign_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Vote Content')),
                ('voted_count', models.IntegerField(default=0, verbose_name='Vote Count')),
                ('voted_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Voted Users')),
            ],
            options={
                'db_table': 't_voteItem',
                'verbose_name': 'voteItem',
                'verbose_name_plural': 'voteItem',
            },
        ),
        migrations.CreateModel(
            name='VoteMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.IntegerField(verbose_name='Vote Done')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vote User ID')),
            ],
            options={
                'db_table': 't_voteMember',
                'verbose_name': 'voteMember',
                'verbose_name_plural': 'voteMember',
            },
        ),
    ]
