# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-23 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0065_auto_20190623_1900'),
        ('business', '0022_remove_businessdocsign_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField(blank=True, null=True, verbose_name='\u5f53\u524d\u8def\u5f84')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('path_docx', models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u8def\u5f841')),
                ('path_html', models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u8def\u5f842')),
                ('file_type', models.CharField(max_length=10, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 't_business_posst',
                'verbose_name': '\u516c\u544a',
                'verbose_name_plural': '\u516c\u544a',
            },
        ),
    ]
