# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-24 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_businesspost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspost',
            old_name='path_docx',
            new_name='docx_id',
        ),
        migrations.RenameField(
            model_name='businesspost',
            old_name='path_html',
            new_name='html_id',
        ),
        migrations.RemoveField(
            model_name='businesspost',
            name='path_id',
        ),
    ]
