# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-24 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_businesspost_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businesspost',
            table='t_business_post',
        ),
    ]
