# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-30 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_vote_business'),
        ('business', '0026_auto_20190624_0156'),
    ]

    operations = [
    ]
