# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_merge_20190630_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='business.VoteItem', verbose_name='Vote Items'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='lost_vote',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vote Lost Count'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='max_vote',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vote Max Count'),
        ),
    ]
