# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_auto_20190630_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemember',
            name='voted',
            field=models.IntegerField(default=0, verbose_name='Vote Done'),
        ),
    ]
