# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20190630_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='items',
            field=models.ManyToManyField(to='business.VoteItem', verbose_name='Vote Items'),
        ),
    ]
