# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20190630_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='method',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vote Method'),
        ),
    ]
