# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_auto_20190630_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='jumper_id',
            field=models.IntegerField(null=True, verbose_name='\u5f53\u524d\u9879\u76ee'),
        ),
    ]
