# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-04 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_auto_20190703_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProjectTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(null=True, verbose_name='\u5f53\u524d\u9879\u76ee')),
                ('process_id', models.IntegerField(null=True, verbose_name='Process')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business')),
            ],
            options={
                'ordering': ('-create_time',),
                'db_table': 't_business_project_track',
                'verbose_name': 'BusinessProjectTrack',
                'verbose_name_plural': 'BusinessProjectTrack',
            },
        ),
    ]
