# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_businessprojecttrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprojecttrack',
            name='process_id',
        ),
        migrations.AddField(
            model_name='businessprojecttrack',
            name='process_type',
            field=models.IntegerField(null=True, verbose_name='Process Type'),
        ),
    ]
