# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20190704_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprojecttrack',
            name='flow_trans_id',
            field=models.IntegerField(null=True, verbose_name='TFlowTrans ID'),
        ),
    ]
