# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-04 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20190704_1321'),
        ('business', '0036_businessprojecttrack_flow_trans_id'),
    ]

    operations = [
    ]
