# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-05 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_merge_20190705_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessteammember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
