# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-08 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_auto_20190708_0933'),
        ('business', '0040_auto_20190708_0546'),
    ]

    operations = [
    ]
