# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_merge_20190708_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdoccontent',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectDoc', verbose_name='BusinessDoc'),
        ),
    ]
