# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-10 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_auto_20190709_0051'),
        ('business', '0042_auto_20190709_0545'),
    ]

    operations = [
    ]
