# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-11 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0043_merge_20190710_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanswer',
            name='question_title',
            field=models.TextField(default=b'', verbose_name='Question Title'),
        ),
        migrations.AddField(
            model_name='businessanswer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
    ]
