# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_auto_20190712_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssurvey',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2019-07-11 16:00:00.000000', verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesssurvey',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
