# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-12 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0045_auto_20190712_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSurveyAnsweredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessSurvey', verbose_name='Business Survey')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'db_table': 't_business_survey_answered_user',
                'verbose_name': 't_business_survey_answered_users',
                'verbose_name_plural': 't_business_survey_answered_users',
            },
        ),
        migrations.AddField(
            model_name='businessanswer',
            name='answeredUser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessSurveyAnsweredUser', verbose_name='Answered User'),
        ),
    ]
