# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-17 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_auto_20190712_1502'),
        ('business', '0044_selectdecideresult'),
    ]

    operations = [
    ]
