# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-30 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_auto_20190719_0321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0047_merge_20190717_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Business')),
                ('guider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Guider')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TRole', verbose_name='Role')),
            ],
            options={
                'db_table': 't_business_guider',
                'verbose_name': 't_business_guider',
                'verbose_name_plural': 't_business_guider',
            },
        ),
    ]
