# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-30 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_merge_20190717_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 't_business_answer',
                'verbose_name': 't_business_answers',
                'verbose_name_plural': 't_business_answers',
            },
        ),
    ]
