# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-31 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0050_guidechatlog_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessguide',
            name='request',
            field=models.ForeignKey(default=1683, on_delete=django.db.models.deletion.CASCADE, related_name='request_set', to=settings.AUTH_USER_MODEL, verbose_name='Request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessguide',
            name='guider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guider_set', to=settings.AUTH_USER_MODEL, verbose_name='Guider'),
        ),
    ]
