# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-31 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0051_auto_20190731_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessguide',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
