# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-01 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_auto_20190719_0321'),
        ('group', '0028_auto_20190515_2240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0052_businessguide_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_ask_chatlog',
                'verbose_name': 'AskChatLog',
                'verbose_name_plural': 'AskChatLog',
            },
        ),
        migrations.CreateModel(
            name='BusinessAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.AllGroups', verbose_name='Group')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.OfficeItems', verbose_name='Office')),
            ],
            options={
                'db_table': 't_business_ask',
                'verbose_name': 't_business_ask',
                'verbose_name_plural': 't_business_ask',
            },
        ),
        migrations.AddField(
            model_name='askchatlog',
            name='ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessAsk', verbose_name='Ask'),
        ),
        migrations.AddField(
            model_name='askchatlog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tuser'),
        ),
    ]
