# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-01 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_auto_20190719_0321'),
        ('business', '0053_auto_20190801_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='askchatlog',
            name='sender_role',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='account.TRole', verbose_name='Sender Role'),
            preserve_default=False,
        ),
    ]
