# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0057_business_parallel_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBillChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(blank=True, null=True, verbose_name='bill_chapter')),
                ('chapter_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='chapter_title')),
                ('chapter_content', models.CharField(blank=True, max_length=512, null=True, verbose_name='chapter_content')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_business_bill_chapter',
                'verbose_name': 'BusinessBillChapter',
                'verbose_name_plural': 'BusinessBillChapter',
            },
        ),
        migrations.CreateModel(
            name='BusinessBillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='bill_name')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='business')),
            ],
            options={
                'db_table': 't_business_bill_list',
                'verbose_name': 'BusinessBillList',
                'verbose_name_plural': 'BusinessBillList',
            },
        ),
        migrations.CreateModel(
            name='BusinessBillPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(blank=True, null=True, verbose_name='part_number')),
                ('part_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='part_title')),
                ('part_content', models.CharField(blank=True, max_length=512, null=True, verbose_name='part_content')),
                ('part_reason', models.CharField(blank=True, max_length=512, null=True, verbose_name='part_reason')),
                ('doc_id', models.IntegerField(blank=True, null=True, verbose_name='doc_id')),
                ('doc_conception', models.IntegerField(blank=True, null=True, verbose_name='doc_conception')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_business_bill_part',
                'verbose_name': 'BusinessBillPart',
                'verbose_name_plural': 'BusinessBillPart',
            },
        ),
        migrations.CreateModel(
            name='BusinessBillPartDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(blank=True, null=True, verbose_name='doc_id')),
                ('doc_conception', models.IntegerField(blank=True, null=True, verbose_name='doc_conception')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('bill_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessBillPart', verbose_name='bill_part')),
            ],
            options={
                'db_table': 't_business_bill_part_doc',
                'verbose_name': 'BusinessBillPartDoc',
                'verbose_name_plural': 'BusinessBillPartDoc',
            },
        ),
        migrations.CreateModel(
            name='BusinessBillSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(blank=True, null=True, verbose_name='section_number')),
                ('section_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='section_title')),
                ('section_content', models.CharField(blank=True, max_length=512, null=True, verbose_name='section_content')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('bill_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessBillChapter', verbose_name='bill_chapter')),
            ],
            options={
                'db_table': 't_business_bill_section',
                'verbose_name': 'BusinessBillSection',
                'verbose_name_plural': 'BusinessBillSection',
            },
        ),
        migrations.AddField(
            model_name='businessbillpart',
            name='bill_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessBillSection', verbose_name='bill_section'),
        ),
        migrations.AddField(
            model_name='businessbillchapter',
            name='bill_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessBillList', verbose_name='bill_list'),
        ),
    ]
