# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0058_auto_20190825_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbillchapter',
            name='bill_list',
        ),
        migrations.RemoveField(
            model_name='businessbillpart',
            name='bill_section',
        ),
        migrations.RemoveField(
            model_name='businessbillpartdoc',
            name='bill_part',
        ),
        migrations.RemoveField(
            model_name='businessbillsection',
            name='bill_chapter',
        ),
        migrations.AddField(
            model_name='businessbillchapter',
            name='sections',
            field=models.ManyToManyField(blank=True, null=True, to='business.BusinessBillSection', verbose_name='sections'),
        ),
        migrations.AddField(
            model_name='businessbilllist',
            name='chapters',
            field=models.ManyToManyField(blank=True, null=True, to='business.BusinessBillChapter', verbose_name='chapters'),
        ),
        migrations.AddField(
            model_name='businessbillpart',
            name='part_docs',
            field=models.ManyToManyField(blank=True, null=True, to='business.BusinessBillPartDoc', verbose_name='part_docs'),
        ),
        migrations.AddField(
            model_name='businessbillsection',
            name='parts',
            field=models.ManyToManyField(blank=True, null=True, to='business.BusinessBillPart', verbose_name='parts'),
        ),
    ]
