# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0059_business_parallel_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessroleallocationstatus',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessTransPath', verbose_name='\u5b9e\u9a8c\u8def\u5f84'),
        ),
    ]
