# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-26 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0060_auto_20190825_2125'),
        ('business', '0059_business_parallel_nodes'),
    ]

    operations = [
    ]
