# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0060_auto_20190825_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbillpartdoc',
            name='doc_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='doc_name'),
        ),
    ]
