# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-18 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0061_businessparallelpassednodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessparallelpassednodes',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessparallelpassednodes',
            name='node',
        ),
        migrations.DeleteModel(
            name='BusinessParallelPassedNodes',
        ),
    ]
