# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-18 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0070_auto_20190813_0036'),
        ('business', '0062_auto_20190818_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessParallelPassedNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u5f53\u524d\u73af\u8282')),
            ],
            options={
                'db_table': 't_business_parallel_passed_node',
                'verbose_name': 'business_parallel_passed_node',
                'verbose_name_plural': 'business_parallel_passed_node',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='parallel_passed_nodes',
            field=models.ManyToManyField(to='business.BusinessParallelPassedNodes'),
        ),
    ]
