# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-26 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0062_auto_20190826_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbillpartdoc',
            name='doc_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='doc_url'),
        ),
    ]
