# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190418_2011'),
        ('business', '0063_businessbillpartdoc_doc_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbillpartdoc',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='businessbillpartdoc',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.UploadFile', verbose_name='doc_id'),
        ),
    ]
