# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-04 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0064_auto_20190826_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbilllist',
            name='edit_mode',
            field=models.IntegerField(blank=True, null=True, verbose_name='edit_mode'),
        ),
    ]
