# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-11 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0065_auto_20190826_1135'),
        ('business', '0064_auto_20190826_2006'),
        ('business', '0061_merge_20190826_0950'),
    ]

    operations = [
    ]
