# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-04 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0065_auto_20190826_1135'),
        ('business', '0061_merge_20190826_0950'),
        ('business', '0065_businessbilllist_edit_mode'),
    ]

    operations = [
    ]
