# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-04 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0066_merge_20190905_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBillPartPartMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(blank=True, null=True, verbose_name='part_number')),
                ('part_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='part_title')),
                ('part_content', models.CharField(blank=True, max_length=512, null=True, verbose_name='part_content')),
                ('part_reason', models.CharField(blank=True, max_length=512, null=True, verbose_name='part_reason')),
                ('doc_id', models.IntegerField(blank=True, null=True, verbose_name='doc_id')),
                ('doc_conception', models.IntegerField(blank=True, null=True, verbose_name='doc_conception')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('part_docs', models.ManyToManyField(blank=True, to='business.BusinessBillPartDoc', verbose_name='part_docs')),
            ],
            options={
                'db_table': 't_business_bill_part_part_mode',
                'verbose_name': 'BusinessBillPartPartMode',
                'verbose_name_plural': 'BusinessBillPartPartMode',
            },
        ),
    ]
