# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-05 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0067_businessbillpartpartmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbilllist',
            name='part_mode_parts',
            field=models.ManyToManyField(blank=True, to='business.BusinessBillPartPartMode', verbose_name='part_mode_parts'),
        ),
    ]
