# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-11 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0067_business_parallel_count'),
        ('business', '0068_businessbilllist_part_mode_parts'),
    ]

    operations = [
    ]
