# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0069_merge_20190911_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssurvey',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='is survey ended'),
        ),
    ]
