# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('all_role', models.BooleanField(verbose_name='\u5141\u8bb8\u4e00\u4eba\u626e\u6f14\u6240\u6709\u89d2\u8272')),
                ('course_id', models.IntegerField(verbose_name='\u8bfe\u7a0b')),
                ('reference', models.PositiveIntegerField(verbose_name='\u6210\u679c\u53c2\u8003\u91ca\u653e\u65b9\u5f0f')),
                ('public_status', models.PositiveIntegerField(verbose_name='\u7533\u8bf7\u4e3a\u516c\u5171\u9879\u76ee\u72b6\u6001')),
                ('level', models.PositiveIntegerField(verbose_name='\u5b9e\u9a8c\u5c42\u6b21')),
                ('entire_graph', models.PositiveIntegerField(verbose_name='\u6d41\u7a0b\u56fe\u5b8c\u6574\u663e\u793a\uff08\u5b8c\u6574\u663e\u793a\u3001\u9010\u6b65\u663e\u793a\uff09')),
                ('type', models.PositiveIntegerField(verbose_name='\u5b9e\u9a8c\u7c7b\u578b')),
                ('can_redo', models.BooleanField(verbose_name='\u662f\u5426\u5141\u8bb8\u91cd\u505a')),
                ('is_open', models.PositiveIntegerField(verbose_name='\u5f00\u653e\u6a21\u5f0f\uff08\u81ea\u7531\u3001\u9650\u65f6\u3001\u6307\u5b9a\u7528\u6237\uff09')),
                ('ability_target', models.PositiveIntegerField(verbose_name='\u80fd\u529b\u76ee\u6807')),
                ('start_time', models.TimeField(verbose_name='\u5f00\u653e\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.TimeField(verbose_name='\u5f00\u653e\u7ed3\u675f\u65f6\u95f4')),
                ('intro', models.TextField(verbose_name='\u9879\u76ee\u7b80\u4ecb')),
                ('purpose', models.TextField(verbose_name='\u5b9e\u9a8c\u76ee\u7684')),
                ('requirement', models.TextField(verbose_name='\u5b9e\u9a8c\u8981\u6c42')),
                ('created_by', models.IntegerField(verbose_name='\u521b\u5efa\u8005')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_project',
                'verbose_name': '\u5b9e\u9a8c\u9879\u76ee',
                'verbose_name_plural': '\u5b9e\u9a8c\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='ProjectDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='\u9879\u76ee')),
                ('name', models.CharField(max_length=64, verbose_name='\u7d20\u6750\u540d\u79f0')),
                ('type', models.CharField(max_length=64, verbose_name='\u7d20\u6750\u7c7b\u578b')),
                ('usage', models.PositiveIntegerField(verbose_name='\u7528\u9014')),
                ('is_initial', models.BooleanField(verbose_name='\u662f\u5426\u4e3a\u521d\u59cb\u7d20\u6750')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_project_doc',
                'verbose_name': '\u9879\u76ee\u7d20\u6750',
                'verbose_name_plural': '\u9879\u76ee\u7d20\u6750',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(verbose_name='\u7d20\u6750')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272')),
                ('project_id', models.IntegerField(verbose_name='\u9879\u76ee')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 't_project_doc_role',
                'verbose_name': '\u9879\u76ee\u7d20\u6750\u5206\u914d',
                'verbose_name_plural': '\u9879\u76ee\u7d20\u6750\u5206\u914d',
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='\u9879\u76ee')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272')),
                ('role_avatar', models.ImageField(storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u89d2\u8272\u5934\u50cf')),
                ('role_file', models.FileField(storage=utils.storage.ImageStorage(), upload_to=b'files/', verbose_name='\u89d2\u8272\u5f62\u8c61\u6587\u4ef6')),
                ('can_terminate', models.BooleanField(verbose_name='\u7ed3\u675f\u73af\u8282\u6743\u9650')),
                ('num', models.PositiveIntegerField(verbose_name='\u5956\u52b1\u6570\u91cf')),
                ('score', models.PositiveIntegerField(verbose_name='\u5956\u52b1\u5206\u6570')),
            ],
            options={
                'db_table': 't_project_role',
                'verbose_name': '\u9879\u76ee\u89d2\u8272\u8bbe\u7f6e',
                'verbose_name_plural': '\u9879\u76ee\u89d2\u8272\u8bbe\u7f6e',
            },
        ),
    ]
