# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170204_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRoleAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272')),
                ('can_terminate', models.BooleanField(verbose_name='\u7ed3\u675f\u73af\u8282\u6743\u9650')),
                ('can_brought', models.BooleanField(verbose_name='\u662f\u5426\u88ab\u5e26\u5165')),
                ('num', models.PositiveIntegerField(verbose_name='\u5956\u52b1\u6570\u91cf')),
                ('score', models.PositiveIntegerField(verbose_name='\u5956\u52b1\u5206\u6570')),
            ],
            options={
                'db_table': 't_project_role_allocation',
                'verbose_name': '\u9879\u76ee\u89d2\u8272\u5206\u914d',
                'verbose_name_plural': '\u9879\u76ee\u89d2\u8272\u5206\u914d',
            },
        ),
        migrations.AlterModelOptions(
            name='projectrole',
            options={'verbose_name': '\u9879\u76ee\u89d2\u8272', 'verbose_name_plural': '\u9879\u76ee\u89d2\u8272'},
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='can_terminate',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='num',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='score',
        ),
        migrations.AddField(
            model_name='projectrole',
            name='category',
            field=models.PositiveIntegerField(default=1, verbose_name='\u7c7b\u522b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrole',
            name='max',
            field=models.IntegerField(default=1, verbose_name='\u6700\u5927\u4eba\u6570'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrole',
            name='min',
            field=models.IntegerField(default=1, verbose_name='\u6700\u5c0f\u4eba\u6570'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrole',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='\u89d2\u8272\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrole',
            name='type',
            field=models.CharField(default=1, max_length=28, verbose_name='\u89d2\u8272\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
