# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170207_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocrole',
            name='project_id',
            field=models.IntegerField(default=1, verbose_name='\u9879\u76ee'),
            preserve_default=False,
        ),
    ]
