# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20170207_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course_id',
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.CharField(default=1, max_length=48, verbose_name='\u8bfe\u7a0b'),
            preserve_default=False,
        ),
    ]
