# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170207_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ability_target',
            field=models.PositiveIntegerField(choices=[(1, '\u7b80\u6613'), (2, '\u57fa\u7840'), (3, '\u8fdb\u9636'), (4, '\u7efc\u5408'), (5, '\u521b\u65b0')], default=1, verbose_name='\u80fd\u529b\u76ee\u6807'),
        ),
        migrations.AlterField(
            model_name='project',
            name='all_role',
            field=models.PositiveIntegerField(choices=[(1, '\u6c38\u8bb8'), (2, '\u4e0d\u6c38\u8bb8')], default=1, verbose_name='\u5141\u8bb8\u4e00\u4eba\u626e\u6f14\u6240\u6709\u89d2\u8272'),
        ),
        migrations.AlterField(
            model_name='project',
            name='can_redo',
            field=models.BooleanField(choices=[(1, '\u6c38\u8bb8'), (2, '\u4e0d\u6c38\u8bb8')], default=1, verbose_name='\u662f\u5426\u5141\u8bb8\u91cd\u505a'),
        ),
        migrations.AlterField(
            model_name='project',
            name='entire_graph',
            field=models.PositiveIntegerField(choices=[(1, '\u5b8c\u6574\u663e\u793a'), (2, '\u9010\u6b65\u663e\u793a')], default=1, verbose_name='\u6d41\u7a0b\u56fe\u5b8c\u6574\u663e\u793a'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.PositiveIntegerField(choices=[(1, '\u81ea\u7531'), (2, '\u9650\u65f6'), (3, '\u6307\u5b9a\u7528\u6237')], default=1, verbose_name='\u5f00\u653e\u6a21\u5f0f'),
        ),
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=1, verbose_name='\u5b9e\u9a8c\u5c42\u6b21'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_status',
            field=models.PositiveIntegerField(choices=[(1, '\u7533\u8bf7'), (2, '\u4e0d\u7533\u8bf7')], default=1, verbose_name='\u7533\u8bf7\u4e3a\u516c\u5171\u9879\u76ee\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reference',
            field=models.PositiveIntegerField(choices=[(1, '\u540c\u6b65'), (2, '\u540e\u6b65'), (3, '\u6700\u540e')], default=1, verbose_name='\u6210\u679c\u53c2\u8003\u91ca\u653e\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '\u52a8\u753b'), (2, '\u7f16\u8f91'), (3, '\u5c55\u793a'), (4, '\u5fc3\u5f97')], default=1, verbose_name='\u5b9e\u9a8c\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='projectdoc',
            name='type',
            field=models.CharField(max_length=32, verbose_name='\u7d20\u6750\u7c7b\u578b'),
        ),
    ]
