# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170215_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdoc',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
