# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20170301_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='step',
            field=models.IntegerField(default=0, verbose_name='\u8bbe\u7f6e\u6b65\u9aa4'),
        ),
    ]
