# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20170331_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='max',
            field=models.IntegerField(default=100, verbose_name='\u6700\u5927\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='min',
            field=models.IntegerField(default=1, verbose_name='\u6700\u5c0f\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='projectroleallocation',
            name='num',
            field=models.PositiveIntegerField(default=0, verbose_name='\u5956\u52b1\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='projectroleallocation',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='\u5956\u52b1\u5206\u6570'),
        ),
    ]
