# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20170331_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='entire_graph',
            field=models.PositiveIntegerField(choices=[(1, '\u5b8c\u6574\u663e\u793a'), (2, '\u9010\u6b65\u663e\u793a'), (3, '\u4e0d\u663e\u793a')], default=1, verbose_name='\u6d41\u7a0b\u56fe\u5b8c\u6574\u663e\u793a'),
        ),
    ]
