# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20170420_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdoc',
            name='is_flow',
            field=models.BooleanField(default=False, verbose_name='\u6d41\u7a0b\u7d20\u6750'),
        ),
    ]
