# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_projectdoc_is_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='\u9879\u76ee')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('jump_project_id', models.IntegerField(verbose_name='\u8df3\u8f6c\u9879\u76ee')),
            ],
            options={
                'db_table': 't_project_jump',
                'verbose_name': '\u9879\u76ee\u73af\u8282\u8df3\u8f6c\u5206\u914d',
                'verbose_name_plural': '\u9879\u76ee\u73af\u8282\u8df3\u8f6c\u5206\u914d',
            },
        ),
    ]
