# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20170905_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdoc',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u6587\u4ef6'), (1, '\u6587\u6863'), (2, '\u56fe\u7247'), (3, '\u89c6\u9891'), (4, '\u97f3\u9891')], default=0, verbose_name='\u6587\u4ef6\u7c7b\u578b'),
        ),
    ]
