# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_projectdoc_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocRoleNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='\u9879\u76ee')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272')),
                ('docs', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6587\u6863id')),
            ],
            options={
                'db_table': 't_project_doc_role_new',
                'verbose_name': '\u9879\u76ee\u73af\u8282\u7d20\u6750\u89d2\u8272\u5206\u914d',
                'verbose_name_plural': '\u9879\u76ee\u73af\u8282\u7d20\u6750\u89d2\u8272\u5206\u914d',
            },
        ),
        migrations.DeleteModel(
            name='ProjectDocNode',
        ),
    ]
