# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_worklog_targets'),
        ('project', '0028_auto_20190424_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='capacity',
            field=models.IntegerField(default=1, verbose_name='\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.TJobType'),
        ),
        migrations.AddField(
            model_name='projectroleallocation',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
    ]
