# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-23 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0060_auto_20190522_2204'),
        ('project', '0028_auto_20190424_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TParts'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_users',
            field=models.ManyToManyField(related_name='projectOpenTargeted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectCreator_set', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
    ]
