# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20190521_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocrole',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
    ]
