# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-23 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20190523_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TCourse', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
