# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_tcourse'),
        ('project', '0030_auto_20190523_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.TRole', verbose_name='\u521b\u5efa\u8005_ROLE'),
            preserve_default=False,
        ),
    ]
