# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_tcourse'),
        ('project', '0031_project_created_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocrole',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='capacity',
            field=models.IntegerField(default=1, verbose_name='\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.TJobType'),
        ),
        migrations.AddField(
            model_name='projectroleallocation',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
    ]
