# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_merge_20190526_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='image_id',
            field=models.IntegerField(null=True, verbose_name='\u89d2\u8272\u5f62\u8c61'),
        ),
    ]
