# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20190526_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='category',
            field=models.PositiveIntegerField(null=True, verbose_name='\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='max',
            field=models.IntegerField(default=100, null=True, verbose_name='\u6700\u5927\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='min',
            field=models.IntegerField(default=1, null=True, verbose_name='\u6700\u5c0f\u4eba\u6570'),
        ),
    ]
