# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20190526_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroleallocation',
            name='can_take_in',
            field=models.BooleanField(default=False, verbose_name='This guy will be taken in this step '),
        ),
    ]
