# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-27 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0055_auto_20190526_2113'),
        ('project', '0037_projectroleallocation_can_take_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_on', models.BooleanField(verbose_name='Look On')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'db_table': 't_project_node_info',
            },
        ),
    ]
