# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-03 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_merge_20190526_1404'),
        ('project', '0038_projectnodeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectUseTo_set', to='account.TParts'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectTargetPart_set', to='account.TParts'),
        ),
    ]
