# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-03 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_projectnodeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroleallocation',
            name='can_start',
            field=models.BooleanField(default=False, verbose_name='Can Start the business'),
        ),
    ]
