# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-03 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20190603_1140'),
        ('project', '0039_projectroleallocation_can_start'),
    ]

    operations = [
    ]
