# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_merge_20190603_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjump',
            name='process_type',
            field=models.IntegerField(default=6, null=True, verbose_name='Process Type'),
        ),
    ]
