# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-13 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0028_auto_20190515_2240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0057_business_parallel_nodes'),
        ('account', '0068_tuser_course_id'),
        ('project', '0042_auto_20190719_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_at', models.DateTimeField(auto_now_add=True, verbose_name='log at')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('request_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Request Url')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TCompany')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.AllGroups')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TRole')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_at'],
                'db_table': 't_project_use_logs',
                'verbose_name': 'Project Use Logs',
                'verbose_name_plural': 'Project Use Log',
            },
        ),
    ]
