# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-17 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0065_tuser_last_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWatchingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Team Name')),
                ('type', models.IntegerField(default=0, verbose_name='Team Type')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Team Members')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TCompany')),
            ],
            options={
                'db_table': 't_student_watching_team',
                'verbose_name': 'StudentWatchingTeams',
                'verbose_name_plural': 'StudentWatchingTeams',
            },
        ),
    ]
