# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190719_0009'),
        ('student', '0004_auto_20190718_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwatchingbusiness',
            name='course',
            field=models.ForeignKey(default=732, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course'),
            preserve_default=False,
        ),
    ]
