# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-21 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_merge_20190717_1903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0066_tuser_teacher_id'),
        ('student', '0005_studentwatchingbusiness_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequestAssistStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='Requested Status')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Watching Business')),
                ('requestedFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_from', to=settings.AUTH_USER_MODEL, verbose_name='Requested From')),
                ('requestedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedTo', to=settings.AUTH_USER_MODEL, verbose_name='Requested To')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TCompany', verbose_name='University')),
            ],
            options={
                'db_table': 't_student_request_assist_status',
                'verbose_name': 'StudentRequestAssistStatuses',
                'verbose_name_plural': 'StudentRequestAssistStatuses',
            },
        ),
    ]
