# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-21 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_studentchatlog_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentchatlog',
            options={'ordering': ['-create_time'], 'verbose_name': 'StudentChatLogs', 'verbose_name_plural': 'StudentChatLogs'},
        ),
        migrations.AlterModelOptions(
            name='studentrequestassiststatus',
            options={'ordering': ['-create_time'], 'verbose_name': 'StudentRequestAssistStatuses', 'verbose_name_plural': 'StudentRequestAssistStatuses'},
        ),
        migrations.AlterModelOptions(
            name='studentwatchingbusiness',
            options={'ordering': ['-create_time'], 'verbose_name': 'StudentWatchingBusinesses', 'verbose_name_plural': 'StudentWatchingBusinesses'},
        ),
        migrations.AlterModelOptions(
            name='studentwatchingteam',
            options={'ordering': ['-create_time'], 'verbose_name': 'StudentWatchingTeams', 'verbose_name_plural': 'StudentWatchingTeams'},
        ),
    ]
