# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-21 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190721_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentchatlog',
            options={'verbose_name': 'StudentChatLogs', 'verbose_name_plural': 'StudentChatLogs'},
        ),
    ]
