# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studenttodolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwatchingbusiness',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course'),
        ),
    ]
