# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-02 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0012_auto_20190803_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWatchingBusinessTeamMemberEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval', models.TextField(default=b'', verbose_name='Team Member Evaluation')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Team Member')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 't_student_watching_business_team_member_eval',
                'verbose_name': 'StudentWatchingBusinessTeamMemberEvals',
                'verbose_name_plural': 'StudentWatchingBusinessTeamMemberEvals',
            },
        ),
        migrations.AddField(
            model_name='studentwatchingbusiness',
            name='teamEval',
            field=models.TextField(default=b'', verbose_name='Team Evaluation'),
        ),
        migrations.AddField(
            model_name='studentwatchingbusinessteammembereval',
            name='stwb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentWatchingBusiness', verbose_name='Student Watching Business'),
        ),
    ]
