# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-20 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0013_auto_20190803_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwatchingteam',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_teams', to=settings.AUTH_USER_MODEL, verbose_name='Team Invited Users'),
        ),
    ]
