# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import student.models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_studentwatchingteam_invited_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchatlog',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='studentchatlog',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.storage.FileStorage(), upload_to=student.models.get_student_doc_upload_to, verbose_name='\u6587\u4ef6'),
        ),
        migrations.AddField(
            model_name='studentchatlog',
            name='file_name',
            field=models.CharField(max_length=64, null=True, verbose_name='\u7d20\u6750\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='studentchatlog',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u6587\u4ef6'), (1, '\u6587\u6863'), (2, '\u56fe\u7247'), (3, '\u89c6\u9891'), (4, '\u97f3\u9891')], default=0, verbose_name='\u6587\u4ef6\u7c7b\u578b'),
        ),
    ]
