# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='\u540d\u79f0')),
                ('animation1', models.ImageField(storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u6e32\u67d3\u52a8\u753b1')),
                ('animation2', models.ImageField(storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u6e32\u67d3\u52a8\u753b2')),
                ('type_label', models.IntegerField(verbose_name='\u5b9e\u9a8c\u7c7b\u578b\u6807\u7b7e')),
                ('task_label', models.CharField(max_length=64, verbose_name='\u5b9e\u9a8c\u4efb\u52a1\u6807\u7b7e')),
                ('copy_from', models.IntegerField(blank=True, null=True, verbose_name='\u590d\u5236\u6d41\u7a0bID')),
                ('diagram', models.ImageField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u6d41\u7a0b\u56fe')),
                ('xml', models.TextField(blank=True, null=True, verbose_name='\u6d41\u7a0b\u56fexml\u6570\u636e')),
                ('created_by', models.IntegerField(verbose_name='\u521b\u5efa\u8005')),
                ('status', models.IntegerField(choices=[(1, '\u672a\u53d1\u5e03'), (2, '\u5df2\u53d1\u5e03')], default=1, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow',
                'verbose_name': '\u6d41\u7a0b',
                'verbose_name_plural': '\u6d41\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='FlowAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24, verbose_name='\u52a8\u4f5c')),
                ('file', models.FileField(storage=utils.storage.ImageStorage(), upload_to=b'files/', verbose_name='\u6587\u4ef6')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_action',
                'verbose_name': '\u52a8\u4f5c',
                'verbose_name_plural': '\u52a8\u4f5c',
            },
        ),
        migrations.CreateModel(
            name='FlowDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=68, verbose_name='\u540d\u79f0')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('usage', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u7528\u9014')),
                ('file', models.FileField(upload_to=b'files/', verbose_name='\u6587\u4ef6')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_docs',
                'verbose_name': '\u7d20\u6750\u6587\u6863',
                'verbose_name_plural': '\u7d20\u6750\u6587\u6863',
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('name', models.CharField(max_length=48, verbose_name='\u73af\u8282\u540d\u79f0')),
                ('condition', models.CharField(blank=True, max_length=68, null=True, verbose_name='\u5e72\u6270')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='\u7a0b\u5e8f\u6a21\u5757')),
                ('look_on', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5141\u8bb8\u65c1\u89c2')),
                ('step', models.IntegerField(blank=True, null=True, verbose_name='\u6392\u5e8f')),
                ('task_id', models.CharField(max_length=16, verbose_name=b'xml\xe4\xb8\xadtask id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_node',
                'verbose_name': '\u5de5\u4f5c\u6d41\u73af\u8282',
                'verbose_name_plural': '\u5de5\u4f5c\u6d41\u73af\u8282',
            },
        ),
        migrations.CreateModel(
            name='FlowPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField(verbose_name='\u573a\u666f')),
                ('position', models.CharField(max_length=32, verbose_name='\u7ad9\u4f4d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_position',
                'verbose_name': '\u573a\u666f\u7ad9\u4f4d',
                'verbose_name_plural': '\u573a\u666f\u7ad9\u4f4d',
            },
        ),
        migrations.CreateModel(
            name='FlowProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='\u540d\u79f0')),
                ('type', models.PositiveIntegerField(verbose_name='\u7c7b\u578b:\u52a8\u753b,\u7f16\u8f91\u5fc3\u5f97,\u67e5\u770b\u6750\u6599,\u751f\u6210\u5b9e\u9a8c\u62a5\u544a')),
                ('file', models.FileField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'files/', verbose_name='\u573a\u666f\u6587\u4ef6')),
                ('image', models.ImageField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u573a\u666f\u622a\u56fe')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_process',
                'verbose_name': '\u7a0b\u5e8f\u6a21\u5757',
                'verbose_name_plural': '\u7a0b\u5e8f\u6a21\u5757',
            },
        ),
        migrations.CreateModel(
            name='FlowRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('name', models.CharField(max_length=32, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('type', models.CharField(max_length=28, verbose_name='\u89d2\u8272\u7c7b\u578b')),
                ('min', models.IntegerField(verbose_name='\u6700\u5c0f\u4eba\u6570')),
                ('max', models.IntegerField(verbose_name='\u6700\u5927\u4eba\u6570')),
                ('category', models.PositiveIntegerField(verbose_name='\u7c7b\u522b')),
                ('avatar', models.ImageField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u5f62\u8c61')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'files/', verbose_name='\u5f62\u8c61\u6587\u4ef6')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_role',
                'verbose_name': '\u73af\u8282\u89d2\u8272',
                'verbose_name_plural': '\u73af\u8282\u89d2\u8272',
            },
        ),
        migrations.CreateModel(
            name='FlowRoleAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272')),
                ('action_id', models.IntegerField(verbose_name='\u52a8\u4f5c')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_role_action',
                'verbose_name': '\u89d2\u8272\u52a8\u4f5c',
                'verbose_name_plural': '\u89d2\u8272\u52a8\u4f5c',
            },
        ),
        migrations.CreateModel(
            name='FlowRoleAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272')),
                ('can_terminate', models.BooleanField(verbose_name='\u7ed3\u675f\u73af\u8282\u6743\u9650')),
                ('can_brought', models.BooleanField(verbose_name='\u662f\u5426\u88ab\u5e26\u5165')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_role_allocation',
                'verbose_name': '\u73af\u8282\u89d2\u8272\u5206\u914d',
                'verbose_name_plural': '\u73af\u8282\u89d2\u8272\u5206\u914d',
            },
        ),
        migrations.CreateModel(
            name='FlowRolePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('node_id', models.IntegerField(verbose_name='\u73af\u8282')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272')),
                ('position_id', models.IntegerField(verbose_name='\u7ad9\u4f4d')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_role_position',
                'verbose_name': '\u89d2\u8272\u7ad9\u4f4d',
                'verbose_name_plural': '\u89d2\u8272\u7ad9\u4f4d',
            },
        ),
        migrations.CreateModel(
            name='FlowTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u540d\u79f0')),
                ('flow_id', models.IntegerField(verbose_name='\u6d41\u7a0b')),
                ('incoming', models.CharField(max_length=32, verbose_name='\u8f93\u5165\u73af\u8282')),
                ('outgoing', models.CharField(max_length=32, verbose_name='\u8f93\u51fa\u73af\u8282')),
                ('conditions', models.CharField(max_length=20, verbose_name='\u6761\u4ef6')),
                ('remark', models.CharField(max_length=256, verbose_name='\u5907\u6ce8')),
                ('sequence_flow_id', models.CharField(max_length=32, verbose_name='xml\u4e2dsequenceFlow')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 't_flow_trans',
                'verbose_name': '\u6d41\u7a0b\u6d41\u8f6c',
                'verbose_name_plural': '\u6d41\u7a0b\u6d41\u8f6c',
            },
        ),
    ]
