# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='\u89d2\u8272\u5f62\u8c61\u540d\u79f0')),
            ],
            options={
                'db_table': 't_role_image',
                'verbose_name': '\u89d2\u8272\u5f62\u8c61',
                'verbose_name_plural': '\u89d2\u8272\u5f62\u8c61',
            },
        ),
        migrations.CreateModel(
            name='RoleImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, '\u7537'), (2, '\u5973')], default=1, verbose_name='\u6027\u522b')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, '\u6b63'), (2, '\u80cc'), (3, '\u4fa7')], default=1, verbose_name='\u65b9\u5411')),
                ('avatar', models.ImageField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u5f62\u8c61')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'files/', verbose_name='\u5f62\u8c61\u6587\u4ef6')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.RoleImage', verbose_name='\u89d2\u8272\u5f62\u8c61')),
            ],
            options={
                'db_table': 't_role_image_file',
                'verbose_name': '\u89d2\u8272\u5f62\u8c61\u6587\u4ef6',
                'verbose_name_plural': '\u89d2\u8272\u5f62\u8c61\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='RoleImageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='\u540d\u79f0')),
            ],
            options={
                'db_table': 't_role_image_type',
                'verbose_name': '\u89d2\u8272\u5f62\u8c61\u7c7b\u578b',
                'verbose_name_plural': '\u89d2\u8272\u5f62\u8c61\u7c7b\u578b',
            },
        ),
        migrations.RemoveField(
            model_name='flowrole',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='flowrole',
            name='file',
        ),
        migrations.AddField(
            model_name='flowrole',
            name='image_id',
            field=models.IntegerField(default=1, verbose_name='\u89d2\u8272\u5f62\u8c61'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleimage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.RoleImageType', verbose_name='\u89d2\u8272\u5f62\u8c61\u7c7b\u578b'),
        ),
    ]
