# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20170204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowposition',
            name='back',
            field=models.BooleanField(default=False, verbose_name='\u80cc\u9762'),
        ),
        migrations.AddField(
            model_name='flowposition',
            name='front',
            field=models.BooleanField(default=False, verbose_name='\u6b63\u9762'),
        ),
        migrations.AddField(
            model_name='flowposition',
            name='side',
            field=models.BooleanField(default=False, verbose_name='\u4fa7\u9762'),
        ),
    ]
