# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20170206_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flownode',
            options={'ordering': ['step'], 'verbose_name': '\u5de5\u4f5c\u6d41\u73af\u8282', 'verbose_name_plural': '\u5de5\u4f5c\u6d41\u73af\u8282'},
        ),
        migrations.AlterField(
            model_name='flow',
            name='animation1',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6e32\u67d3\u52a8\u753b1'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='animation2',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6e32\u67d3\u52a8\u753b2'),
        ),
    ]
