# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170207_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrole',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, '\u5f8b\u5e08'), (2, '\u6cd5\u5b98'), (3, '\u516c\u52a1\u5458'), (4, '\u68c0\u5bdf\u5b98'), (5, '\u516c\u8bc1\u5458'), (6, '\u7acb\u6cd5\u8005'), (7, '\u5176\u4ed6')], verbose_name='\u7c7b\u522b'),
        ),
    ]
