# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20170207_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowposition',
            name='process_id',
        ),
        migrations.AddField(
            model_name='flowposition',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowProcess', verbose_name='\u573a\u666f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowprocess',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '\u52a8\u753b'), (2, '\u7f16\u8f91'), (3, '\u5c55\u793a'), (4, '\u5fc3\u5f97')], verbose_name='\u7c7b\u578b'),
        ),
    ]
