# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20170208_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flownode',
            name='process_id',
        ),
        migrations.AddField(
            model_name='flownode',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowProcess', verbose_name='\u7a0b\u5e8f\u6a21\u5757'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='look_on',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5141\u8bb8\u65c1\u89c2'),
        ),
    ]
