# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20170208_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdocs',
            name='type',
            field=models.CharField(default=1, max_length=32, verbose_name='\u7d20\u6750\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
