# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_flowdocs_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowroleallocation',
            name='flow_id',
        ),
        migrations.RemoveField(
            model_name='flowroleallocation',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='flowroleallocation',
            name='role_id',
        ),
        migrations.AddField(
            model_name='flowroleallocation',
            name='flow',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='workflow.Flow', verbose_name='\u6d41\u7a0b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowroleallocation',
            name='node',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowroleallocation',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowRole', verbose_name='\u89d2\u8272'),
            preserve_default=False,
        ),
    ]
