# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20170208_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowaction',
            old_name='action',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='flowaction',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to=b'files/', verbose_name='\u6587\u4ef6'),
        ),
    ]
