# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20170208_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='\u540d\u79f0')),
                ('cmd', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u547d\u4ee4')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowProcess', verbose_name='\u573a\u666f')),
            ],
            options={
                'db_table': 't_process_action',
                'verbose_name': '\u573a\u666f\u52a8\u4f5c',
                'verbose_name_plural': '\u573a\u666f\u52a8\u4f5c',
            },
        ),
        migrations.RemoveField(
            model_name='flowaction',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='flowaction',
            name='file',
        ),
        migrations.RemoveField(
            model_name='flowaction',
            name='update_time',
        ),
        migrations.AddField(
            model_name='flowaction',
            name='cmd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u547d\u4ee4'),
        ),
    ]
