# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20170209_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['-create_time'], 'verbose_name': '\u6d41\u7a0b', 'verbose_name_plural': '\u6d41\u7a0b'},
        ),
        migrations.AddField(
            model_name='flowdocs',
            name='content',
            field=models.TextField(default='', verbose_name='\u5185\u5bb9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowrole',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, '\u5f8b\u5e08'), (2, '\u6cd5\u5b98'), (3, '\u516c\u52a1\u5458'), (4, '\u68c0\u5bdf\u5b98'), (5, '\u516c\u8bc1\u5458'), (6, '\u7acb\u6cd5\u8005'), (99, '\u5176\u4ed6')], verbose_name='\u7c7b\u522b'),
        ),
    ]
