# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20170215_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdocs',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
