# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20170216_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='flownodedocs',
            name='del_flag',
            field=models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664'),
        ),
    ]
