# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_flownodedocs_del_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdocs',
            name='usage',
            field=models.PositiveIntegerField(choices=[(1, '\u64cd\u4f5c\u6307\u5357'), (2, '\u5173\u8054\u6587\u4ef6'), (3, '\u6a21\u7248'), (4, '\u6750\u6599'), (5, '\u516c\u6587'), (6, '\u6210\u679c\u53c2\u8003'), (7, '\u9879\u76ee\u63d0\u793a')], default=1, verbose_name='\u7528\u9014'),
        ),
    ]
