# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_auto_20170221_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowposition',
            name='code_position',
            field=models.CharField(default='', max_length=32, verbose_name='\u4ee3\u7801\u4e2d\u7684\u7ad9\u4f4d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowposition',
            name='position',
            field=models.CharField(max_length=32, verbose_name='flash\u4e2d\u7684\u7ad9\u4f4d'),
        ),
    ]
