# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20170221_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processaction',
            name='cmd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u547d\u4ee4'),
        ),
    ]
