# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20170310_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowaction',
            options={'ordering': ['order'], 'verbose_name': '\u529f\u80fd\u52a8\u4f5c', 'verbose_name_plural': '\u529f\u80fd\u52a8\u4f5c'},
        ),
        migrations.AlterModelOptions(
            name='processaction',
            options={'ordering': ['order'], 'verbose_name': '\u573a\u666f\u52a8\u4f5c', 'verbose_name_plural': '\u573a\u666f\u52a8\u4f5c'},
        ),
        migrations.AddField(
            model_name='flow',
            name='step',
            field=models.IntegerField(default=0, verbose_name='\u8bbe\u7f6e\u6b65\u9aa4'),
        ),
    ]
