# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_auto_20170321_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowposition',
            name='back',
        ),
        migrations.RemoveField(
            model_name='flowposition',
            name='front',
        ),
        migrations.RemoveField(
            model_name='flowposition',
            name='side',
        ),
    ]
