# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_auto_20170416_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flownode',
            options={'ordering': ['name'], 'verbose_name': '\u5de5\u4f5c\u6d41\u73af\u8282', 'verbose_name_plural': '\u5de5\u4f5c\u6d41\u73af\u8282'},
        ),
        migrations.AlterField(
            model_name='flownode',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.FlowProcess', verbose_name='\u7a0b\u5e8f\u6a21\u5757'),
        ),
        migrations.AlterField(
            model_name='flowposition',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.FlowProcess', verbose_name='\u573a\u666f'),
        ),
        migrations.AlterField(
            model_name='flowroleaction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.FlowAction', verbose_name='\u529f\u80fd\u52a8\u4f5c'),
        ),
        migrations.AlterField(
            model_name='processaction',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.FlowProcess', verbose_name='\u573a\u666f'),
        ),
        migrations.AlterField(
            model_name='roleimage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.RoleImageType', verbose_name='\u89d2\u8272\u5f62\u8c61\u7c7b\u578b'),
        ),
    ]
