# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0034_processroleaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processroleaction',
            name='action',
        ),
        migrations.AddField(
            model_name='processroleaction',
            name='actions',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u573a\u666f\u52a8\u753b\u914d\u7f6e'),
        ),
    ]
