# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_auto_20170612_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowprocess',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '\u52a8\u753b'), (2, '\u7f16\u8f91'), (3, '\u5c55\u793a'), (4, '\u5fc3\u5f97'), (5, '\u6295\u7968'), (6, '\u8df3\u8f6c')], verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='processroleaction',
            name='actions',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u573a\u666f\u52a8\u753b\u914d\u7f6e'),
        ),
    ]
