# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_auto_20170613_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowposition',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, '\u666e\u901a'), (1, '\u62a5\u544a\u5e2d')], default=0, verbose_name='\u7ad9\u4f4d\u7c7b\u578b'),
        ),
    ]
