# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_auto_20170803_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRoleActionNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u529f\u80fd\u52a8\u4f5c')),
                ('del_flag', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Flow', verbose_name='\u6d41\u7a0b')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowNode', verbose_name='\u73af\u8282')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.FlowRole', verbose_name='\u89d2\u8272')),
            ],
            options={
                'db_table': 't_flow_role_action_new',
                'verbose_name': '\u89d2\u8272\u52a8\u4f5c',
                'verbose_name_plural': '\u89d2\u8272\u52a8\u4f5c',
            },
        ),
        migrations.RemoveField(
            model_name='flowrolefunction',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='flowrolefunction',
            name='node',
        ),
        migrations.RemoveField(
            model_name='flowrolefunction',
            name='role',
        ),
        migrations.DeleteModel(
            name='FlowRoleFunction',
        ),
    ]
