# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_processroleactionnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowprocess',
            options={'ordering': ['sort'], 'verbose_name': '\u7a0b\u5e8f\u6a21\u5757', 'verbose_name_plural': '\u7a0b\u5e8f\u6a21\u5757'},
        ),


    ]
