# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_auto_20170823_0945'),
    ]

    operations = [

    ]
