# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0043_auto_20170831_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowprocess',
            name='can_switch',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u80fd\u5207\u6362\u89c6\u89d2'),
        ),

        migrations.DeleteModel(
            name='FlowRoleAction',
        ),
        migrations.DeleteModel(
            name='ProcessRoleAction',
        ),
    ]
