# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_auto_20170904_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowprocess',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5c55\u793a\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='flowdocs',
            name='usage',
            field=models.PositiveIntegerField(choices=[(0, '\u65e0'), (1, '\u64cd\u4f5c\u6307\u5357'), (2, '\u5173\u8054\u6587\u4ef6'), (3, '\u6a21\u7248'), (4, '\u6750\u6599'), (5, '\u516c\u6587'), (6, '\u6210\u679c\u53c2\u8003'), (7, '\u9879\u76ee\u63d0\u793a')], default=0, verbose_name='\u7528\u9014'),
        ),
    ]
