# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0047_auto_20190404_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='is_public',
            field=models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u516c\u5f00'),
        ),
    ]
