# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-04 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0049_auto_20190503_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrole',
            name='image_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u89d2\u8272\u5f62\u8c61'),
        ),
        migrations.AlterField(
            model_name='flowrole',
            name='max',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6700\u5927\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='flowrole',
            name='min',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6700\u5c0f\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='flowrole',
            name='type',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='\u89d2\u8272\u7c7b\u578b'),
        ),
    ]
