# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-04 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0051_auto_20190504_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowdocs',
            options={'ordering': ['-create_time'], 'verbose_name': '\u7d20\u6750\u6587\u6863', 'verbose_name_plural': '\u7d20\u6750\u6587\u6863'},
        ),
    ]
