# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0052_auto_20190504_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowroleallocation',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
    ]
