# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-05 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0053_flowroleallocation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowroleallocation',
            name='can_take_in',
            field=models.BooleanField(default=False, verbose_name='Take Part in this guy'),
        ),
    ]
