# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0054_flowroleallocation_can_take_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowroleallocation',
            name='can_take_in',
            field=models.BooleanField(default=False, verbose_name='This guy will be taken in this step '),
        ),
    ]
