# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_merge_20190526_1404'),
        ('workflow', '0056_flowroleallocation_can_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.TRole', verbose_name='\u521b\u5efa\u8005_ROLE'),
            preserve_default=False,
        ),
    ]
