# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0059_processroleallocationaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowroleposition',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
    ]
