# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0063_auto_20190618_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowroleallocation',
            name='image_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u89d2\u8272\u5f62\u8c61'),
        ),
    ]
