# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0064_flowroleallocation_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowprocess',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '\u52a8\u753b'), (2, '\u7f16\u8f91'), (3, '\u5c55\u793a'), (4, '\u5fc3\u5f97'), (5, '\u6295\u7968'), (6, '\u8df3\u8f6c'), (7, '\u516c\u793a')], verbose_name='\u7c7b\u578b'),
        ),
    ]
