# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0065_auto_20190623_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectDecideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTitle', models.CharField(max_length=50, verbose_name='ItemTitle')),
                ('itemDescription', models.CharField(max_length=100, verbose_name='ItemDescription')),
            ],
            options={
                'db_table': 't_selectDecideItem',
                'verbose_name': '\u5224\u65ad\u4e0e\u9009\u62e9_Item',
                'verbose_name_plural': '\u5224\u65ad\u4e0e\u9009\u62e9_Item',
            },
        ),
    ]
