# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-12 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0066_selectdecideitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowNodeSelectDecide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowNode_id', models.IntegerField(verbose_name='FlowNodeId')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('mode', models.IntegerField(default=0, verbose_name='Mode')),
                ('items', models.ManyToManyField(to='workflow.SelectDecideItem')),
            ],
            options={
                'db_table': 't_flow_node_selectDecide',
                'verbose_name': '\u5224\u65ad\u4e0e\u9009\u62e9',
                'verbose_name_plural': '\u5224\u65ad\u4e0e\u9009\u62e9',
            },
        ),
    ]
