# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-14 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0067_flownodeselectdecide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownodeselectdecide',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flownodeselectdecide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='selectdecideitem',
            name='itemDescription',
            field=models.CharField(max_length=255, verbose_name='ItemDescription'),
        ),
        migrations.AlterField(
            model_name='selectdecideitem',
            name='itemTitle',
            field=models.CharField(max_length=255, verbose_name='ItemTitle'),
        ),
    ]
