# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-12 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0068_auto_20190714_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='flownode',
            name='parallel_node_start',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5141\u8bb8\u65c1\u89c2'),
        ),
    ]
