# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0069_flownode_parallel_node_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='flownode',
            name='is_parallel_merging',
            field=models.BooleanField(default=False, verbose_name='Parallel_node_end'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='parallel_node_start',
            field=models.BooleanField(default=False, verbose_name='Parallel_node_start'),
        ),
    ]
